# -*- mode: ruby -*-
# vi: set ft=ruby :

machines = {
	"scmIntegration" => {"memory"=>"2048", "cpus"=>"1", "ip" => "10" , "installDocker" => "no"},
	"pipeline" => {"memory"=>"4096", "cpus"=>"1", "ip" => "20", "installDocker" => "yes" },
	"homolog" => {"memory"=>"1024", "cpus"=>"1", "ip" => "30" , "installDocker" => "no"},
	"production" => {"memory"=>"1024", "cpus"=>"1", "ip" => "40" , "installDocker" => "no"},
}

Vagrant.configure("2") do |config|
  config.vm.box = "debian/buster64"
  
  machines.each do |name,conf|
    config.vm.define "#{name}" do |machine|
      machine.vm.network "private_network", ip: "192.168.88.#{conf["ip"]}"
      machine.vm.hostname = "#{name}.dexter.com.br"
      machine.vm.provider "virtualbox" do |vb|
        vb.cpus = "#{conf["cpus"]}"
        vb.customize ["modifyvm", :id, "--groups", "/524-CI/-CD"]
	vb.memory = "#{conf["memory"]}"
	vb.name = "#{name}"
	vb.gui = false
      end
  
     config.vm.provision "shell", inline: <<-SHELL
       sudo apt-get install  vim chrony apt-transport-https ca-certificates gnupg-agent software-properties-common -y  
       sudo sed -i 's/#PasswordAuthentication/PasswordAuthentication/g' /etc/ssh/sshd_config
       sudo systemctl restart sshd
     SHELL
  
     
 
     if "#{conf["installDocker"]}" == "yes" then
        config.vm.provision "shell", inline: <<-SHELL
          sudo apt-get install apt-transport-https ca-certificates curl gnupg-agent software-properties-common -y
          sudo wget -q -O - https://download.docker.com/linux/debian/gpg | sudo apt-key add 
          sudo echo "deb [arch=amd64] https://download.docker.com/linux/debian $(lsb_release -cs) stable" > /etc/apt/sources.list.d/docker.list
          sudo apt-get update -y
          sudo apt-get install  docker-ce docker-ce-cli containerd.io -y
        SHELL
     end

    end
  end



end
